### ISSUE TITLE
Create Sign up Function (React)

### ISSUE THREAD

**Issue by salomaogabriel** [salomaogabriel/salt-venture#13]
Create a function that will make a POST Request to the /users to create an user
- Make the submit button have a loading animation
- If there are any errors, stop the loading animation
- Before Making the post request:
- Make sure to validate the fields (Use Regular Expressions)
- Password must be strong
- Username can only have letters, numbers, _, ( No weird letters, aka ä, å,œ, ô, ã, etc)
- Email must be in an email format.
- If any validations go, wrong, display error to the user in the right field
- Make the Request
- If there's an error, show the error on the right field ( eg: This email already exists )
- If there's NO error, save user info in a cookie, then redirect to /

**Comment by NicholasIzosimov** [comment]
Finished :)
